"use client"
import { Inter } from "next/font/google";
import "./globals.css";
//import Login from "@/Login/Login";
//import { Provider } from "react-redux";
//import { store } from "@/Reducer/store";
import { useReducer } from "react";
//import { Provider } from "@/context/appContext";
//import { reducer } from "@/Reducer/Reducer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  //const [state, dispatch] = useReducer(reducer,init)
  return (
    <html lang="en">
      <body>
    
       {children}
   
       
        </body>
    </html>
  );
}
